#!/usr/bin/env python
# coding: utf-8

from __future__ import absolute_import

TASKSTATS_CMD_GET = 1
#TASKSTATS_VERSION = 8 # o_O some structs changes...
TASKSTATS_GENL_NAME = 'TASKSTATS'
TASKSTATS_GENL_VERSION = 1
TASKSTATS_CMD_ATTR_PID = 1
TASKSTATS_CMD_ATTR_REGISTER_CPUMASK = 3

TASKSTATS_TYPE_PID = 1
TASKSTATS_TYPE_TGID = 2
TASKSTATS_TYPE_STATS = 3
TASKSTATS_TYPE_AGGR_PID = 4
TASKSTATS_TYPE_AGGR_TGID = 5

